config/routes.rb
Rails.application.routes.draw do


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :admins do
    devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords',
    registrations: 'admins/regitrations'
    }
    get '/' => 'homes#top'
    resources :items, only: [:create, :index, :new, :edit, :update,:show]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :orders, only: [:index, :show, :update] do
     resources :order_details, only: [:update]
    end
  end

  scope module: :public do
    devise_for :customers, controllers: {
    sessions: 'public/sessions',
    passwords: 'public/passwords',
    registrations: 'public/registrations'
    }
    root to: 'homes#top'
    get '/about' => 'homes#about'
    get '/customer/customer_edit' =>"customers#edit", as: 'edit_customer'
    patch '/customers/update' => "customers#update", as: 'update_customer'
    resource :customers, only: [:show]
    resources :items, only: [:index, :show]
    resources :cart_items, only: [:index, :create, :update, :destroy]
    delete '/cart_items/:id/destroy_all' => 'cart_items#destroy_all', as: 'cart_items_destroy_all'
    get 'customers/unsubscribe' => 'customers#unsubscribe'
    put "/customers/:id/withdraw" => "customers#withdraw", as: 'customer_withdraw'
    get '/orders/complete' => 'orders#complete', as: 'orders_complete'
    resources :orders, only: [:index, :show, :new, :create]
    post '/orders/confirm' => 'orders#confirm', as: 'orders_confirm'

  end

end

app/models/address.rb
class Address < ApplicationRecord
  
  belongs_to :customer
  
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,# :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  
  belongs_to :customer
  belongs_to :item
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  
  def active_for_authentication?
    super && (self.is_deleted == false)
  end
  
end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :items

  attachment :image

end

app/models/item.rb
class Item < ApplicationRecord
  
  has_many :order_items, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  belongs_to :genre
  
  attachment :image
end

app/models/order.rb
class Order < ApplicationRecord

  has_many :order_items, dependent: :destroy
  belongs_to :customer
  enum order_status: {
    入金待ち: 0,
    入金確認: 1,
    制作中: 2,
    発送準備中: 3,
    発送済: 4
  }

  enum payment_method: {
    クレジットカード: 0,
    銀行振込: 1
  }
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  
  belongs_to :item
  belongs_to :order
  
  enum making_status: {
    着手不可: 0,
    制作待ち: 1,
    制作中: 2,
    制作完了: 3
  }
  
end

app/controllers/admins/genres_controller.rb
class Admins::GenresController < ApplicationController
  layout 'admins'
  
  def index
    @genres = Genre.all
    @genre = Genre.new
  end
  
  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admins_genres_path
  end
  
  def edit
    
  end
  
  def update
    
  end
  
  
  private
  
  def genre_params
    params.require(:genre).permit(:name, :is_active)
  end
  
end

app/controllers/admins/homes_controller.rb
class Admins::HomesController < ApplicationController
  layout 'admins'

  def top
    @count = Order.where(created_at: Time.zone.now.beginning_of_day..Time.zone.now.end_of_day).count
  end

end

app/controllers/admins/items_controller.rb
class Admins::ItemsController < ApplicationController
  layout 'admins'

  def new
    @item = Item.new
  end


  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admins_item_path(@item.id)
  end

  def index
    @items = Item.all.page(params[:page]).per(10)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admins_item_path(@item.id)
  end

  private

  def item_params
    params.require(:item).permit(:name, :introduction, :image, :genre_id, :non_taxed_price, :is_active)
  end
end

app/controllers/admins/orders_controller.rb
class Admins::OrdersController < ApplicationController
  layout 'admins'

  def index
    @orders = Order.all.page(params[:page]).per(10)
  end

  def show
    @order = Order.find(params[:id])
    @order_items = @order.order_items
    @order_item = OrderItem.find(params[:id])
  end

  def update
    @order = Order.find(params[:id])
    @order_items = OrderItem.where(order_id: @order.id)
    
    if @order.update(orders_params)

      if @order.order_status == "入金確認"

        @order_items.each do |order_item|
         order_item.update(making_status: "制作待ち")
        end
      end
    end
    redirect_to admins_order_path
  end

  private

  def orders_params
    params.require(:order).permit(:postal_code, :address, :name, :shipping_cost, :total_payment, :order_status, :payment_method, :customer_id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?




  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [
        :last_name,
        :first_name,
        :last_name_kana,
        :first_name_kana,
        :postal_code,
        :address,
        :telephone_number
        ])
    end
end

app/helpers/admins/customers_helper.rb
module Admins::CustomersHelper
end

app/helpers/admins/genres_helper.rb
module Admins::GenresHelper
end

app/helpers/admins/homes_helper.rb
module Admins::HomesHelper
end

app/helpers/admins/items_helper.rb
module Admins::ItemsHelper
end

app/helpers/admins/order_details_helper.rb
module Admins::OrderDetailsHelper
end

app/helpers/admins/orders_helper.rb
module Admins::OrdersHelper
end

app/helpers/admins/testadmin_helper.rb
module Admins::TestadminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admins/genres/index.html.erb
<h3><span class="label label-default">ジャンル一覧・追加</span></h1>

<%= form_with model:@genre, url: admins_genres_path, local:true do |f| %>

  <label>
    ジャンル
    <%= f.text_field :name %>
  </label>

  <label>
    <%=f.radio_button :is_active, TRUE %> 有効
  </label>

  <label>
    <%=f.radio_button :is_active, FALSE %> 無効
  </label>

  <%= f.submit '追加', class: "btn btn-primary" %>

<% end %>


<table>
  <tr>
    <th>ジャンル</th>
    <th>状態</th>
    <th></th>
  </tr>

<% @genres.each do |genre| %>
  <tr>
    <td><%= genre.name %></td>
    <td><%= genre.is_active %></td>
    <td><%= link_to '編集する', edit_admins_genre_path(genre.id), class: "btn btn-primary" %></td>
  </tr>
<% end %>
</table>

app/views/admins/homes/top.html.erb
<div class="admins-top container">
  <h3><span class="label label-default">管理者画面</span></span></h1>
  <p>本日の注文件数       <%= link_to @count, admins_orders_path %>件</p>
</div>

app/views/admins/items/edit.html.erb
<div class="container">
  <h3><span class="label label-default">商品編集</span></span></h1>

  <div class="admins-edit">
    <div class="admins-edit-image">
     <%= attachment_image_tag @item, :image, format: 'jpg', class: "profile-img", size: "300x200" %>
    </div>


    <%= form_with model:@item, url: admins_item_path, local:true do |f| %>

    <table class="admins-item-edit-table">
      <tr>
        <th>
          商品名
        </th>
        <td>
          <%= f.text_field :name %>
        </td>
      </tr>



      <tr>
        <th>
          商品説明
        </th>
        <td>
          <%= f.text_area :introduction %>
        </td>
      </tr>



      <tr>
        <th>
          ジャンル
        </th>
        <td>
          <%= f.collection_select :genre_id, Genre.all, :id, :name %>
        </td>
      </tr>



      <tr>
        <th>
          税抜価格
        </th>
        <td>
          <%= f.text_field :non_taxed_price %>
        </td>
      </tr>


      <tr>
        <th>
          販売ステータス
        </th>
        <td>
          <%= f.select :is_active, [['販売中', true], ['売切', false]] %>
        </td>
      </tr>
    </table>


    <div class="item-edit-btn pull-right">
        <%= f.submit '変更を保存', class: "btn btn-lg btn-primary" %>
    </div>

    <% end %>
  </div>
</div>

app/views/admins/items/index.html.erb
<div class="container">
  <h3><span class="label label-default">商品一覧</span></span></h1>

  <%= link_to '+', new_admins_item_path, class: "new_button" %>


  <table class="admins-items-index table-bordered">
    <tr>
      <th>商品ID</th>
      <th>商品名</th>
      <th>税抜価格</th>
      <th>ジャンル</th>
      <th>ステータス</th>
    </tr>

    <% @items.each do |item| %>
      <tr>
        <td><%= item.id %></td>
        <td><%= link_to item.name, admins_item_path(item.id) %></td>
        <td><%= item.non_taxed_price %></td>
        <td><%= item.genre.name %></td>
        <td><%= item.is_active %></td>
      </tr>
    <% end %>
  </table>
</div>

<div class="admins-items-paginate text-center">
  <%= paginate @items %>
</div>

app/views/admins/items/new.html.erb
<div class="container">
  <h3><span class="label label-default">商品新規登録</span></span></h1>

  <div class="admins-item-new">
    <%= form_with model:@item, url: admins_items_path, method: :POST, local:true do |f| %>
    <table class="admins-item-new-table center-block">

      <tr>
        <th>商品名</th>
        <td><%= f.text_field :name %></td>
      </tr>

      <tr>
        <th>商品説明</th>
        <td><%= f.text_area :introduction %></td>
      </tr>

      <tr>
        <th>商品画像</th>
        <td><%= f.attachment_field :image %></td>
      </tr>

      <tr>
        <th>ジャンル</th>
        <td><%= f.collection_select :genre_id, Genre.all, :id, :name %></td>
      </tr>

      <tr>
        <th>税抜価格</th>
        <td><%= f.text_field :non_taxed_price %></td>
      </tr>

      <tr>
        <th>販売ステータス</th>
        <td><%= f.select :is_active, [['販売中', true], ['売切', false]] %></td>
      </tr>

      </table>
      <div class="item_submit">
        <%= f.submit '新規登録', class: "btn btn-lg btn-primary pull-right" %>
      </div>

    <% end %>
  </div>
</div>

app/views/admins/items/show.html.erb
<div class="container">
 <h3><span class="label label-default">商品詳細</span></span></h1>
 <div class="admins-item_show">
   <div class="admins-item-show-image">
    <%= attachment_image_tag @item, :image, format: 'jpg', class: "profile-img", size: "300x200" %>
   </div>
    <table class="admins-item-show-table">
      <tr>
        <td>商品名</td>
        <td><%= @item.name %></td>
      </tr>

       <tr>
        <td>商品説明</td>
        <td><%= @item.introduction %></td>
      </tr>

      <tr>
        <td>ジャンル</td>
        <td><%= @item.name %></td>
      </tr>

       <tr>
        <td>税込価格(税抜単価)</td>
        <td><%= (@item.non_taxed_price * 1.1).round %>円(<%= @item.non_taxed_price %>)円</td>
      </tr>

       <tr>
        <td>販売ステータス</td>
        <td><%= @item.is_active %></td>
      </tr>
    </table>
 </div>

 <div class="admins-item-edit-link pull-right">
  <%= link_to '編集する', edit_admins_item_path(@item.id), class: "btn btn-lg btn-primary" %>
 </div>
</div>

app/views/admins/orders/index.html.erb
<div class="container">
  <h3><span class="label label-default">注文履歴一覧</span></h1>

  <table class="admins-order-index-table table-bordered">
    <thead>
      <tr>
        <th>購入日時</th>
        <th>購入者</th>
        <th>注文個数</th>
        <th>注文ステータス</th>
      </tr>
    </thead>

    <% @orders.each do |order| %>
    <tbody>
      <tr>
        <td><%= link_to order.created_at.strftime("%Y-%m-%d %H:%M:%S"),  admins_order_path(order.id), data: {"turbolinks" => false} %></td>
        <td><%= order.customer.last_name + order.customer.first_name %></td>
        <td><%= order.order_items.sum(:count) %></td>
        <td><%= order.order_status_i18n %></td>
      </tr>
    </tbody>
    <% end %>
  </table>

  <div class="admins-items-paginate text-center">
    <%= paginate @orders %>
  </div>
</div>

app/views/admins/orders/show.html.erb
<div class="container">
 <h3><span class="label label-default">注文履歴詳細</span></h1>

 <table>
   <tr>
     <th>購入者</th>
     <td><%= link_to @order.customer.last_name + @order.customer.first_name,  admins_customer_path(@order.customer_id) %></td>
   </tr>

   <tr>
     <th>配送先</th>
     <td>
       〒<%= @order.postal_code %>
       <%= @order.address %><br>
       <%= @order.customer.last_name + @order.customer.first_name %>
      </td>
   </tr>

   <tr>
     <th>支払方法</th>
     <td><%= @order.payment_method %></td>
   </tr>

   <%= form_with model:@order, url: admins_order_path(@order.id), method: :patch, local:true do |f| %>
   <tr>
     <th>注文ステータス</th>
     <td>
       <%= f.select :order_status, Order.order_statuses.keys.to_a, {} %>
       <%= f.submit "更新", class: "btn btn-primary" %>
     </td>
   </tr>
   <% end %>
 </table>


  <div class="row">
    <div class="col-xs-8">
      <table class="admins-order-show-table table-bordered">
        <thead>
          <tr>
            <th>商品</th>
            <th>単価(税込)</th>
            <th>個数</th>
            <th>小計</th>
            <th>制作ステータス</th>
            <th></th>
          </tr>
        </thead>
    
       <% @order_items.each do |order_item| %>
        <tbody>
          <tr>
            <td><%= order_item.item.name %></td>
            <td><%= order_item.tax_in_purchased_price %></td>
            <td><%= order_item.count %></td>
            <td><%= order_item.tax_in_purchased_price * order_item.count %></td>
    
            <%= form_with(model: [@order, order_item], url: admins_order_order_detail_path(@order.id, order_item.id), method: :patch, local: true) do |f| %>
            <td>
              <%= f.select :making_status, OrderItem.making_statuses.keys.to_a, {} %>
            </td>
            <td>
              <%= f.submit "更新", class: "btn btn-primary" %>
            </td>
            <% end %>
          </tr>
        </tbody>
        <% end %>
      </table>
    </div>
    
    <div class="col-xs-4">
      <table class="admins-item-total">
        <tr>
          <th>商品合計</th>
          <td><%= @order.total_payment %>円</td>
        </tr>
    
        <tr>
          <th>送料</th>
          <td>800円</td>
        </tr>
    
        <tr>
          <th>請求金額合計</th>
          <td><%= @order.total_payment + 800 %>円</td>
        </tr>
      </table>
    </div>
  </div>
</div>