config/routes.rb
Rails.application.routes.draw do


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :admins do
    devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords',
    registrations: 'admins/regitrations'
    }
    get '/' => 'homes#top'
    resources :items, only: [:create, :index, :new, :edit, :update,:show]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :orders, only: [:index, :show, :update] do
     resources :order_details, only: [:update]
    end
  end

  scope module: :public do
    devise_for :customers, controllers: {
    sessions: 'public/sessions',
    passwords: 'public/passwords',
    registrations: 'public/registrations'
    }
    root to: 'homes#top'
    get '/about' => 'homes#about'
    get '/customer/customer_edit' =>"customers#edit", as: 'edit_customer'
    patch '/customers/update' => "customers#update", as: 'update_customer'
    resource :customers, only: [:show]
    resources :items, only: [:index, :show]
    resources :cart_items, only: [:index, :create, :update, :destroy]
    delete '/cart_items/:id/destroy_all' => 'cart_items#destroy_all', as: 'cart_items_destroy_all'
    get 'customers/unsubscribe' => 'customers#unsubscribe'
    put "/customers/:id/withdraw" => "customers#withdraw", as: 'customer_withdraw'
    get '/orders/complete' => 'orders#complete', as: 'orders_complete'
    resources :orders, only: [:index, :show, :new, :create]
    post '/orders/confirm' => 'orders#confirm', as: 'orders_confirm'

  end

end

app/models/address.rb
class Address < ApplicationRecord
  
  belongs_to :customer
  
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,# :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  
  belongs_to :customer
  belongs_to :item
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  
  def active_for_authentication?
    super && (self.is_deleted == false)
  end
  
end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :items

  attachment :image

end

app/models/item.rb
class Item < ApplicationRecord
  
  has_many :order_items, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  belongs_to :genre
  
  attachment :image
end

app/models/order.rb
class Order < ApplicationRecord

  has_many :order_items, dependent: :destroy
  belongs_to :customer
  enum order_status: {
    入金待ち: 0,
    入金確認: 1,
    制作中: 2,
    発送準備中: 3,
    発送済: 4
  }

  enum payment_method: {
    クレジットカード: 0,
    銀行振込: 1
  }
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  
  belongs_to :item
  belongs_to :order
  
  enum making_status: {
    着手不可: 0,
    制作待ち: 1,
    制作中: 2,
    制作完了: 3
  }
  
end

app/controllers/admins/customers_controller.rb
class Admins::CustomersController < ApplicationController
  layout 'admins'

  def index
    @customers = Customer.all.page(params[:page]).per(10)
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admins_customer_path(@customer.id)
  end

  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email, :is_deleted)
  end

end

app/controllers/admins/genres_controller.rb
class Admins::GenresController < ApplicationController
  layout 'admins'
  
  def index
    @genres = Genre.all
    @genre = Genre.new
  end
  
  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admins_genres_path
  end
  
  def edit
    
  end
  
  def update
    
  end
  
  
  private
  
  def genre_params
    params.require(:genre).permit(:name, :is_active)
  end
  
end

app/controllers/admins/homes_controller.rb
class Admins::HomesController < ApplicationController
  layout 'admins'

  def top
    @count = Order.where(created_at: Time.zone.now.beginning_of_day..Time.zone.now.end_of_day).count
  end

end

app/controllers/admins/items_controller.rb
class Admins::ItemsController < ApplicationController
  layout 'admins'

  def new
    @item = Item.new
  end


  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admins_item_path(@item.id)
  end

  def index
    @items = Item.all.page(params[:page]).per(10)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admins_item_path(@item.id)
  end

  private

  def item_params
    params.require(:item).permit(:name, :introduction, :image, :genre_id, :non_taxed_price, :is_active)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?




  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [
        :last_name,
        :first_name,
        :last_name_kana,
        :first_name_kana,
        :postal_code,
        :address,
        :telephone_number
        ])
    end
end

app/helpers/admins/customers_helper.rb
module Admins::CustomersHelper
end

app/helpers/admins/genres_helper.rb
module Admins::GenresHelper
end

app/helpers/admins/homes_helper.rb
module Admins::HomesHelper
end

app/helpers/admins/items_helper.rb
module Admins::ItemsHelper
end

app/helpers/admins/order_details_helper.rb
module Admins::OrderDetailsHelper
end

app/helpers/admins/orders_helper.rb
module Admins::OrdersHelper
end

app/helpers/admins/testadmin_helper.rb
module Admins::TestadminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admins/customers/edit.html.erb
<div class="container">
  <h3><span class="label label-default"><%= @customer.last_name + @customer.first_name %>さんの会員情報編集</span></h1>

  <%= form_with model:@customer, url: admins_customer_path, local:true do |f| %>

    <table class="admins-customer-edit-table">
      <tr>
        <th>会員ID</th>
        <td><%= @customer.id %></td>
      </tr>

      <tr>
        <th>氏名</th>
        <td>
          <%= f.text_field :last_name %>
          <%= f.text_field :first_name %>
        </td>
      </tr>

      <tr>
        <th>フリガナ</th>
        <td>
          <%= f.text_field :last_name_kana %>
          <%= f.text_field :first_name_kana %>
        </td>
      </tr>

      <tr>
        <th>郵便番号</th>
        <td><%= f.text_field :postal_code %></td>
      </tr>

      <tr>
        <th>住所</th>
        <td><%= f.text_field :address, size: 50 %></td>
      </tr>

      <tr>
        <th>電話番号</th>
        <td><%= f.text_field :telephone_number %></td>
      </tr>

      <tr>
        <th>メールアドレス</th>
        <td><%= f.text_field :email %></td>
      </tr>

      <tr>
        <th>会員ステータス</th>
        <td>
          <%= f.radio_button :is_deleted, FALSE %> 有効
          <%= f.radio_button :is_deleted, TRUE %> 無効
        </td>
      </tr>

      </table>
      <%= f.submit '変更を保存する', class: "btn btn-primary" %>
    <% end %>
</div>

app/views/admins/customers/index.html.erb
<div class="container">
  <h3><span class="label label-default">会員一覧</span></h1>

  <table class="admins-customer-index-table table-bordered">
    <tr>
      <th>会員ID</th>
      <th>氏名</th>
      <th>メールアドレス</th>
      <th>ステータス</th>
    </tr>

  <% @customers.each do |customer| %>
    <tr>
      <td><%= customer.id %></td>
      <td><%= link_to customer.last_name + customer.first_name, admins_customer_path(customer.id) %></td>
      <td><%= customer.email %></td>
      <td><%= customer.is_deleted %></td>
    </tr>
  <% end %>
  </table>

  <div class="admins-items-paginate text-center">
    <%= paginate @customers %>
  </div>
</div>

app/views/admins/customers/show.html.erb
<div class="container">
  <h3><span class="label label-default"><%= @customer.last_name + @customer.first_name %>さんの会員詳細</span></h1>

  <table class="admins-customer-show-table">
    <tr>
      <th>顧客ID</th>
      <td>
        <%= @customer.id %>
        <% if @customer.is_deleted == false %>
          <p class="label label-primary">有効会員</p>
        <% end %>
      </td>
    </tr>

    <tr>
      <th>氏名</th>
      <td><%= @customer.last_name + @customer.first_name %></td>
    </tr>

    <tr>
      <th>フリガナ</th>
      <td><%= @customer.last_name_kana + @customer.first_name_kana %></td>
    </tr>

    <tr>
      <th>郵便番号</th>
      <td><%= @customer.postal_code %></td>
    </tr>

    <tr>
      <th>住所</th>
      <td><%= @customer.address %></td>
    </tr>

    <tr>
      <th>電話番号</th>
      <td><%= @customer.telephone_number %></td>
    </tr>

    <tr>
      <th>メールアドレス</th>
      <td><%= @customer.email %></td>
    </tr>
  </table>

  <div class="admins-customer-show-btn">
    <%= link_to '編集する', edit_admins_customer_path, class: "btn btn-primary" %>
    <%= link_to '注文履歴一覧を見る', admins_orders_path, class: "btn btn-primary" %>
  </div>

</div>