config/routes.rb
Rails.application.routes.draw do


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :admins do
    devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords',
    registrations: 'admins/regitrations'
    }
    get '/' => 'homes#top'
    resources :items, only: [:create, :index, :new, :edit, :update,:show]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :orders, only: [:index, :show, :update] do
     resources :order_details, only: [:update]
    end
  end

  scope module: :public do
    devise_for :customers, controllers: {
    sessions: 'public/sessions',
    passwords: 'public/passwords',
    registrations: 'public/registrations'
    }
    root to: 'homes#top'
    get '/about' => 'homes#about'
    get '/customer/customer_edit' =>"customers#edit", as: 'edit_customer'
    patch '/customers/update' => "customers#update", as: 'update_customer'
    resource :customers, only: [:show]
    resources :items, only: [:index, :show]
    resources :cart_items, only: [:index, :create, :update, :destroy]
    delete '/cart_items/:id/destroy_all' => 'cart_items#destroy_all', as: 'cart_items_destroy_all'
    get 'customers/unsubscribe' => 'customers#unsubscribe'
    put "/customers/:id/withdraw" => "customers#withdraw", as: 'customer_withdraw'
    get '/orders/complete' => 'orders#complete', as: 'orders_complete'
    resources :orders, only: [:index, :show, :new, :create]
    post '/orders/confirm' => 'orders#confirm', as: 'orders_confirm'

  end

end

app/models/address.rb
class Address < ApplicationRecord
  
  belongs_to :customer
  
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,# :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  
  belongs_to :customer
  belongs_to :item
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  
  def active_for_authentication?
    super && (self.is_deleted == false)
  end
  
end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :items

  attachment :image

end

app/models/item.rb
class Item < ApplicationRecord
  
  has_many :order_items, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  belongs_to :genre
  
  attachment :image
end

app/models/order.rb
class Order < ApplicationRecord

  has_many :order_items, dependent: :destroy
  belongs_to :customer
  enum order_status: {
    入金待ち: 0,
    入金確認: 1,
    制作中: 2,
    発送準備中: 3,
    発送済: 4
  }

  enum payment_method: {
    クレジットカード: 0,
    銀行振込: 1
  }
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  
  belongs_to :item
  belongs_to :order
  
  enum making_status: {
    着手不可: 0,
    制作待ち: 1,
    制作中: 2,
    制作完了: 3
  }
  
end

app/controllers/admins/homes_controller.rb
class Admins::HomesController < ApplicationController
  layout 'admins'

  def top
    @count = Order.where(created_at: Time.zone.now.beginning_of_day..Time.zone.now.end_of_day).count
  end

end

app/controllers/admins/items_controller.rb
class Admins::ItemsController < ApplicationController
  layout 'admins'

  def new
    @item = Item.new
  end


  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admins_item_path(@item.id)
  end

  def index
    @items = Item.all.page(params[:page]).per(10)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admins_item_path(@item.id)
  end

  private

  def item_params
    params.require(:item).permit(:name, :introduction, :image, :genre_id, :non_taxed_price, :is_active)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?




  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [
        :last_name,
        :first_name,
        :last_name_kana,
        :first_name_kana,
        :postal_code,
        :address,
        :telephone_number
        ])
    end
end

app/helpers/admins/customers_helper.rb
module Admins::CustomersHelper
end

app/helpers/admins/genres_helper.rb
module Admins::GenresHelper
end

app/helpers/admins/homes_helper.rb
module Admins::HomesHelper
end

app/helpers/admins/items_helper.rb
module Admins::ItemsHelper
end

app/helpers/admins/orders_helper.rb
module Admins::OrdersHelper
end

app/helpers/admins/testadmin_helper.rb
module Admins::TestadminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/layouts/admins.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>naganocake</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
<body>
  <header>
    <div class="container">
      <h1 class="header-title navbar navbar-nav navbar-left">LOGO</h1>
      <ul class="header-list nav navbar-nav navbar-right">
        <% if admins_admin_signed_in? %>
          <li>
            <%= link_to admins_items_path do %>
              <button class="btn btn-primary">商品一覧</button>
            <% end %>
          </li>
          <li>
            <%= link_to admins_customers_path do %>
              <button class="btn btn-success">会員一覧</button>
            <% end %>
          </li>
          <li>
            <%= link_to admins_orders_path do %>
              <button class="btn btn-info">注文履歴一覧</button>
            <% end %>
          </li>
          <li>
            <%= link_to  admins_genres_path do %>
              <button class="btn btn-danger">ジャンル一覧</button>
            <% end %>
          </li>
          <li>
            <%= link_to  destroy_admins_admin_session_path, :method => :delete do %>
              <button class="btn btn-warning">ログアウト</button>
            <% end %>
          </li>
        <% else %>
          <li>
            <%= link_to '/about' do %>
              <button class="btn btn-primary">About</button>
            <% end %>
          </li>
          <li>
            <%= link_to admins_items_path do %>
              <button class="btn btn-success">商品一覧</button>
            <% end %>
          </li>
          <li>
            <%= link_to new_customer_registration_path do %>
              <button class="btn btn-info">新規登録</button>
            <% end %>
          </li>
          <li>
            <%= link_to new_admins_admin_session_path do %>
              <button class="btn btn-warning">ログイン</button>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </header>

  <%= yield %>
<footer></footer>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>naganocake</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
<body>
  <header>
    <div class="container">
      <h1 class="header-title navbar navbar-nav navbar-left">LOGO</h1>
      <ul class="header-list nav navbar-nav navbar-right">
        <% if customer_signed_in? %>
          <li>
            <%= link_to  customers_path do %>
              <button class="btn btn-primary">マイページ</button>
            <% end %>
          </li>
          <li>
            <%= link_to items_path do %>
              <button class="btn btn-success">商品一覧</button>
            <% end %>
          </li>
          <li>
            <%= link_to cart_items_path do %>
              <button class="btn btn-info">カート</button>
            <% end %>
          </li>
          <li>
            <%= link_to  destroy_customer_session_path, :method => :delete do %>
              <button class="btn btn-warning">ログアウト</button>
            <% end %>
          </li>
        <% else %>
          <li>
            <%= link_to '/about' do %>
              <button class="btn btn-primary">About</button>
            <% end %>
          </li>
          <li>
            <%= link_to items_path do %>
              <button class="btn btn-success">商品一覧</button>
            <% end %>
          </li>
          <li>
            <%= link_to new_customer_registration_path do %>
              <button class="btn btn-info">新規登録</button>
            <% end %>
          </li>
          <li>
            <%= link_to new_customer_session_path do %>
              <button class="btn btn-warning">ログイン</button>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </header>

  <%= yield %>


  <footer></footer>

</body>
</html>